{
 "title": "Documents Deep Checkup",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Documents",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(pid_v3) as \"Total documents\",\n  count(distinct pid_v3) as \"Total documents (no repetition)\"\nFROM\n  doc_deep_checkup\nWHERE\n  $__timeFilter(created_at);"
    }
   ]
  },
  {
   "title": "Total complete documents",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(pid_v3) as \"Total complete documents\",\n  count(distinct pid_v3) as \"Total complete documents (no repetition)\"\nFROM\n  doc_deep_checkup\nWHERE\n  status = 'complete' \n  AND $__timeFilter(created_at)\n  ;"
    }
   ]
  },
  {
   "title": "Total partial documents",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(pid_v3) as \"Total partial documents\",\n  count(distinct pid_v3) as \"Total partial documents (no repetition)\"\nFROM\n  doc_deep_checkup\nWHERE\n  status = 'partial'\n  AND $__timeFilter(created_at)\n  ;"
    }
   ]
  },
  {
   "title": "Total missing documents",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(pid_v3) as \"Total missing documents\",\n  count(distinct pid_v3) as \"Total missing documents (no repetition)\"\nFROM\n  doc_deep_checkup\nWHERE\n  status = 'missing'\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "DOC DEEP CHECKUP: DOCUMENTS WHICH HTML IS INCOMPLETE ",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at, pid_v3, pid_v2_doc, previous_pid_v2_doc, detail::json#>'{summary,web html,total incomplete}' as \"total absent components\", detail::json->'summary' as \"SUMMARY\", detail::json->'detail' as \"DETAIL\"\nFROM\n  doc_deep_checkup\nWHERE\n  status = 'partial'\n  AND (detail::json#>>'{summary,web html,total incomplete}')::int > 0 \n  AND $__timeFilter(created_at)\n  ;"
    }
   ]
  },
  {
   "title": "DOC DEEP CHECKUP: DOCUMENTS WHICH WEB HTML IS  UNAVAILABLE",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at, pid_v3, pid_v2_doc, previous_pid_v2_doc, detail::json#>'{summary,web html,total}' as \"total web html\", detail::json#>'{summary,web html,total unavailable}' AS \"total web html unavailable\", detail::json->'summary' as \"SUMMARY\", detail::json->'detail' as \"DETAIL\"\nFROM\n  doc_deep_checkup\nWHERE\n  status = 'partial'\n  AND (detail::json#>>'{summary,web html,total unavailable}')::int > 0\n  AND $__timeFilter(created_at)\n  ;"
    }
   ]
  },
  {
   "title": "DOC DEEP CHECKUP: DOCUMENTS WHICH WEB PDF IS UNAVAILABLE",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at, pid_v3, pid_v2_doc, previous_pid_v2_doc, detail::json#>'{summary,web pdf,total}' as \"total web pdf\", detail::json#>'{summary,web pdf,total unavailable}' AS \"total web pdf unavailable\",  detail::json->'summary' as \"SUMMARY\", detail::json->'detail' as \"DETAIL\"\nFROM\n  doc_deep_checkup\nWHERE\n  status = 'partial'\n  AND (detail::json#>>'{summary,web pdf,total unavailable}')::int > 0\n  AND $__timeFilter(created_at)\n  ;"
    }
   ]
  },
  {
   "title": "DOC DEEP CHECKUP: DOCUMENTS WITH UNAVAILABLE RENDITIONS",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at, pid_v3, pid_v2_doc, previous_pid_v2_doc, detail::json#>'{summary,renditions,total}' as \"total renditions\", detail::json#>'{summary,renditions,total unavailable}' AS \"total renditions unavailable\", detail::json->'summary' as \"SUMMARY\", detail::json->'detail' as \"DETAIL\"\nFROM\n  doc_deep_checkup\nWHERE\n  status = 'partial'\n  AND (detail::json#>>'{summary,renditions,total unavailable}')::int > 0\n  AND $__timeFilter(created_at)\n  ;"
    }
   ]
  },
  {
   "title": "DOC DEEP CHECKUP: DOCUMENTS WITH UNAVAILABLE ASSETS",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at, pid_v3, pid_v2_doc, previous_pid_v2_doc, detail::json#>'{summary,assets,total}' as \"total assets\", detail::json#>'{summary,assets,total unavailable}' AS \"total assets unavailable\", detail::json->'summary' as \"SUMMARY\", detail::json->'detail' as \"DETAIL\"\nFROM\n  doc_deep_checkup\nWHERE\n  status = 'partial'\n  AND (detail::json#>>'{summary,assets,total unavailable}')::int > 0\n  AND $__timeFilter(created_at)\n  ;"
    }
   ]
  },
  {
   "title": "DOC DEEP CHECKUP: MISSING documents",
   "type": "table",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at, pid_v3, pid_v2_doc, previous_pid_v2_doc, detail::json->'summary' as \"SUMMARY\", detail::json->'detail' as \"DETAIL\"\nFROM\n  doc_deep_checkup\nWHERE\n  status = 'missing'\n  AND $__timeFilter(created_at)\n  ;"
    }
   ]
  }
 ]
}