{
 "title": "Processamento SPF - Produção",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "_data_source", "label": "Data Source", "query": "postgres" },
   {
    "name": "pre_sync_dag_run_id",
    "label": "Processamento",
    "query": "SELECT pre_sync_dag_run FROM xml_documents WHERE $__timeFilter(created_at) order by created_at desc;"
   },
   {
    "name": "pacotes_extraidos_dag_run",
    "label": "Pacote",
    "query": "select\n    dag_run\nfrom\n    xml_documents\nwhere\n    $__timeFilter(created_at)\n    AND pre_sync_dag_run LIKE concat('%', $pre_sync_dag_run_id,  '%')\norder by\n    created_at desc;"
   },
   { "name": "pid_v3", "label": "XML PID V3" },
   { "name": "show_only_documents_errors", "label": "Filtrar documentos por", "query": "Sem Falha,Falha" },
   { "name": "show_link_by_type", "label": "Filtrar Relacionamentos por", "query": "Regular,Ex-Ahead" },
   { "name": "_airflow_host", "label": "_airflow_host", "query": "airflow.scielo.br" },
   { "name": "_kernel_host", "label": "kernel_host", "query": "kernel.scielo.br" }
  ]
 },
 "panels": [
  { "title": "Processamentos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quantidade de documentos processados",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) AS \"Total\",\n  count(distinct file_name) as \"Únicos\"\nFROM\n  xml_documents\nWHERE\n  $__timeFilter(created_at) and dag_run LIKE concat('%', $pacotes_extraidos_dag_run, '%') AND pre_sync_dag_run LIKE concat('%', $pre_sync_dag_run_id, '%');"
    }
   ]
  },
  {
   "title": "Quantidade de documentos processados com sucesso",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(pid) AS \"Total\",\n  count(distinct pid) as \"Únicos\"\nFROM\n  xml_documents\nWHERE\n  $__timeFilter(created_at)\n  AND dag_run LIKE concat('%', $pacotes_extraidos_dag_run, '%')\n  AND pre_sync_dag_run LIKE concat('%', $pre_sync_dag_run_id, '%')\n  AND failed is FALSE;"
    }
   ]
  },
  {
   "title": "Quantidade de documentos processados com falha",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) AS \"Total\",\n  count(distinct file_name) AS \"Únicos\"\nFROM\n  xml_documents\nWHERE\n  $__timeFilter(created_at) and dag_run LIKE concat('%', $pacotes_extraidos_dag_run, '%') AND pre_sync_dag_run LIKE concat('%', $pre_sync_dag_run_id, '%') and failed is true;"
    }
   ]
  },
  {
   "title": "Documentos processados ao longo do tempo",
   "type": "graph",
   "description": "Contabiliza a quantidade de XML processados no decorrer do tempo. O eixo Y exibe a quantidade de artigos e o eixo X o horário de processamento.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(id) AS \"Registrados com sucesso\"\nFROM xml_documents\nWHERE\n  $__timeFilter(created_at) AND\n  dag_run LIKE concat('%', $pacotes_extraidos_dag_run, '%') AND\n  pre_sync_dag_run LIKE concat('%', $pre_sync_dag_run_id, '%') AND\n  deletion is false\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(id) AS \"Removidos com sucesso\"\nFROM xml_documents\nWHERE\n  $__timeFilter(created_at) AND\n  dag_run LIKE concat('%', $pacotes_extraidos_dag_run, '%') AND\n  pre_sync_dag_run LIKE concat('%', $pre_sync_dag_run_id, '%') AND\n  deletion is true AND\n  failed is false\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(id) AS \"Falhas na remoção\"\nFROM xml_documents\nWHERE\n  $__timeFilter(created_at) AND\n  dag_run LIKE concat('%', $pacotes_extraidos_dag_run, '%') AND\n  pre_sync_dag_run LIKE concat('%', $pre_sync_dag_run_id, '%') AND\n  deletion is true AND\n  failed is true\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Artigos processados por pacote",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select\n    dag_run,\n    count(*) as \"Quantidade\",\n    package_name as \"Pacote\",\n    --(\n    --    case\n    --        failed\n    --        when true then 'Falha'\n     --       when false then 'Sucesso'\n     --   end\n    --) as \"Status\"\n    file_name as \"File\", \n    failed as \"Status\"\n    --to_char(created_at, 'dd-MM-YYYY') as \"Data\"\nFROM\n    xml_documents\nWHERE\n    $__timeFilter(created_at)\n    and dag_run LIKE concat('%', $pacotes_extraidos_dag_run, '%')\n    AND pre_sync_dag_run LIKE concat('%', $pre_sync_dag_run_id, '%')\n    AND (\n          pid LIKE concat('%', nullif('$pid_v3', ''), '%') OR pid is null\n        )\n    AND (CASE\n                    WHEN ${show_only_documents_errors:singlequote} ILIKE 'Falha' THEN\n                      failed = TRUE\n                    WHEN ${show_only_documents_errors:singlequote} ILIKE 'Sem falha' THEN\n                      failed = False\n                    ELSE\n                     failed IN (False, True)\n                  END)\nGROUP BY\n    dag_run,\n    failed,\n    \"File\",\n    \"Pacote\"\nORDER BY \"Quantidade\" DESC\n"
    }
   ]
  },
  {
   "title": "XML Processados",
   "type": "table-old",
   "description": "Lista de arquivos xml processados. Inclui o nome do arquivo XML, o pid v3 (identificador do documento), status de falha ao registrar no Kernel e o texto da falha.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  --file_name as \"Nome\",\n  dag_run,\n  pid as \"PID v3\",\n  (case\n    deletion when true then 'Sim' else 'Não' end\n  ) as \"Remoção\",\n  --(case\n  --  failed when true then 'Sim' else '-' end\n  --) as \"Falhou?\",\n  error as \"Falha\",\n  created_at as \"Data\"\nFROM xml_documents\nWHERE\n  $__timeFilter(created_at)\n  AND dag_run LIKE concat('%', $pacotes_extraidos_dag_run, '%')\n  AND pre_sync_dag_run LIKE concat('%', $pre_sync_dag_run_id, '%') \n  AND (pid LIKE concat('%', nullif('$pid_v3', ''), '%') or pid is null)\n  --AND failed = (CASE\n  --                  WHEN '$show_only_documents_errors' ILIKE 'Falha' THEN\n  --                    TRUE\n  --                  WHEN '$show_only_documents_errors' ILIKE 'Sem falha' THEN\n  --                    False\n  --                  ELSE\n  --                    False\n  --                END)\n    AND (CASE\n                    WHEN ${show_only_documents_errors:singlequote} ILIKE 'Falha' THEN\n                      failed = TRUE\n                    WHEN ${show_only_documents_errors:singlequote} ILIKE 'Sem falha' THEN\n                      failed = False\n                    ELSE\n                     failed IN (False, True)\n                  END) \nORDER BY created_at DESC"
    }
   ]
  },
  { "title": "Documents Bundle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Quantide de documentos relacionados com seus respectivos bundles",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(bundle_id)\nFROM\n  xml_documentsbundle\nWHERE\n  $__timeFilter(created_at)\n  AND dag_run LIKE concat('%', $pacotes_extraidos_dag_run, '%')\n  AND pre_sync_dag_run LIKE concat($pre_sync_dag_run_id)\n  AND failed is false\n  AND removed is false"
    }
   ]
  },
  {
   "title": "Quantidade de falhas ao relacionar documentos e bundles",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(bundle_id)\nFROM\n  xml_documentsbundle\nWHERE\n  $__timeFilter(created_at)\n  AND dag_run LIKE concat('%', $pacotes_extraidos_dag_run, '%')\n  AND pre_sync_dag_run LIKE concat($pre_sync_dag_run_id)\n  AND failed is true"
    }
   ]
  },
  {
   "title": "Quantidade de documentos ex ahead",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct pid)\nFROM\n  xml_documentsbundle\nWHERE\n  $__timeFilter(created_at)\n  AND dag_run LIKE concat('%', $pacotes_extraidos_dag_run, '%')\n  AND pre_sync_dag_run LIKE concat($pre_sync_dag_run_id)\n  AND ex_ahead is true"
    }
   ]
  },
  {
   "title": "Quantidade de sucessos por bundle",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "select\n    count(id) as \"Quantidade\",\n    bundle_id as \"Bundle\"\nFROM\n    xml_documentsbundle\nWHERE\n    $__timeFilter(created_at)\n    and dag_run LIKE concat('%', $pacotes_extraidos_dag_run, '%')\n    AND pre_sync_dag_run LIKE concat('%', $pre_sync_dag_run_id, '%')\n    AND pid LIKE concat('%', nullif('$pid_v3', ''), '%')\n    AND failed is false\nGROUP BY\n    bundle_id\nORDER BY\n    \"Quantidade\"\n--    dag_run,\n--    failed,"
    }
   ]
  },
  {
   "title": "Quantidade de falhas por bundle",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "rawSql": "select\n    count(*) as \"Quantidade\",\n    bundle_id as \"Bundle\",\n    dag_run,\n    error\nFROM\n    xml_documentsbundle\nWHERE\n    $__timeFilter(created_at)\n    and dag_run LIKE concat('%', $pacotes_extraidos_dag_run, '%')\n    AND pre_sync_dag_run LIKE concat('%', $pre_sync_dag_run_id, '%')\n    AND pid LIKE concat('%', nullif('$pid_v3', ''), '%')\n    AND failed is true\nGROUP BY\n    bundle_id,\n    dag_run,\n    error\nORDER BY\n    \"Quantidade\""
    }
   ]
  },
  {
   "title": "Lista de artigos e seus respectivos bundles",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "rawSql": "select\n    pid as \"PID v3\",\n    bundle_id as \"Document Bundle\",\n    (case ex_ahead when true then 'Sim' else '-' end) as \"Ex ahead of print\"\nFROM\n    xml_documentsbundle\nWHERE\n    $__timeFilter(created_at)\n    AND dag_run LIKE concat('%', $pacotes_extraidos_dag_run, '%')\n    AND pre_sync_dag_run LIKE concat('%', $pre_sync_dag_run_id, '%')\n    AND pid LIKE concat('%', nullif('$pid_v3', ''), '%')\n    AND failed is false\n    AND ex_ahead = (CASE\n                    WHEN '$show_link_by_type' ILIKE 'Regular' THEN\n                      FALSE\n                    WHEN '$show_link_by_type' ILIKE 'Ex-Ahead' THEN\n                      True\n                    ELSE\n                      False\n                  END)"
    }
   ]
  }
 ]
}