{
 "title": "Disponibilidade de \"sci_pages\"",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "SCI_PAGES: Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(uri) as \"Total SCI_PAGES\",\n  count(distinct uri) as \"Total SCI_PAGES (no repetition)\"\nFROM\n  sci_pages_availability\nWHERE\n  $__timeFilter(created_at);"
    }
   ]
  },
  {
   "title": "SCI_PAGES: total unavailable",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(uri) as \"Total SCI_PAGES Unavailable\",\n  count(distinct uri) as \"Total SCI_PAGES unavailable (no repetition)\"\nFROM\n  sci_pages_availability\nWHERE\n    failed is true\n\tAND $__timeFilter(created_at);"
    }
   ]
  },
  {
   "title": "SCI_PAGES: total available",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(uri) as \"Total SCI_PAGES Available\",\n  count(distinct uri) as \"Total SCI_PAGES available (no repetition)\"\nFROM\n  sci_pages_availability\nWHERE\n    failed is false\n    AND $__timeFilter(created_at);"
    }
   ]
  },
  {
   "title": "sci_pages que falharam",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  uri, detail::json->'end time' AS \"access date/time\", detail::json->'status code' AS \"status code\", detail::json->'duration' as \"duration\"\nFROM\n  sci_pages_availability\nWHERE\n  failed is TRUE\n  AND $__timeFilter(created_at)\n  ;"
    }
   ]
  }
 ]
}